### ISSUE TITLE
Praise Jah in the Moonlight Album Cover Font

### ISSUE THREAD

**Issue by princeofaxum** [raeytype/exodus-abyssinica#1]
Hello,

I was on the ethiopia subreddit and I saw someone asking about the font used in a picture of YG Marley's (Bob Marley's grandson) new album "Praise Jah in the Moonlight".

This album cover also uses Fidal styled Latin alphabet just like the Exodus cover, and I ended up here looking in my search for that font. I'm not sure if this helpful but just in case you need some inspiration, particularly for the letters not featured in the Exodus cover. Here is the link to the Wikipedia article which has the album cover.

https://en.wikipedia.org/wiki/Praise_Jah_in_the_Moonlight

**Comment by dyacob** [comment]
Hello,

Sorry for being slow to respond.  I did look into the letter mappings on the YG Marley album and saw that he made different letter mapping choices than on the Exodus album, so there was a loss of compatibility.  Also within the title you can see that "h" is first "አ", then "ዝ", and back to "አ".  "i" is also done two different ways, so that's a little confusing and I put it off for later since I was in hurry to complete the Exodus style.

The YG Marley mappings are good for inspiration like you said for the missing letters, and I think especially for lowercase.  I'll think about that for an update, also for a future font that is based on the YG Marley album approach.

thanks,  

-Daniel


Anyway, I might try it later in a separate font, I wouldn't to mix the two approaches.
